# Generated by Django 3.2.9 on 2021-12-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebilldetail',
            name='sale_item',
        ),
    ]
