# Generated by Django 3.2.9 on 2021-12-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('unit', models.CharField(default='PCS', max_length=5)),
                ('quantity', models.PositiveIntegerField(default=0, editable=False)),
                ('brand', models.CharField(default='Generic', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Stock',
            },
        ),
    ]
